# Generated by Django 4.0.3 on 2022-03-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enviro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('type', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
