# Generated by Django 4.0.3 on 2022-03-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enviro',
            new_name='Environment',
        ),
    ]
